name: gg_json
description: gg_json allows easy JSON manipulation via a/b/c paths for read/write.
version: 1.0.0
repository: https://github.com/inlavigo/gg_json.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  gg_args: ^1.1.8
  gg_log: ^1.0.0
  gg_process: ^1.0.7
  path: ^1.8.0

dev_dependencies:
  gg: ^1.0.1
  gg_capture_print: ^1.0.4
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0
