name: gg_json
description: gg_json allows easy JSON manipulation via a/b/c paths for read/write.
version: 2.0.0
repository: https://github.com/inlavigo/gg_json.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
